name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}

      - name: Add SSH known hosts
        run: |
          echo 'de1.webforger.fr $(ssh-keyscan -H de1.webforger.fr 2>&1)' >> ~/.ssh/known_hosts

      - name: Run chatbotUpdate.sh
        run: |
          ssh -o StrictHostKeyChecking=no debian@de1.webforger.fr "cd /home/debian/ && bash chatbotUpdate.sh"
